from fastapi import APIRouter, HTTPException, status
# from fastapi.templating import Jinja2Templates

from models.users import User, UserSignIn


user_router = APIRouter(tags=["User"])

users = {}
# templates = Jinja2Templates(directory="templates/")


@user_router.post("/signup")
async def sign_user_up(data: User) -> dict:
    if data.email in users:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Email already exists")

    users[data.email] = data
    
    return {"message": "User successfully registered!"}
    
    
@user_router.post("/signin")
async def sign_user_in(user: UserSignIn) -> dict:
    if user.email not in users:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User does not exist")
    
    if users[user.email].password != user.password:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Wrong credential passed")
    return {"message": "User signed in successfully"}